# Generated by Django 5.0.4 on 2024-04-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='level',
            field=models.CharField(default='begineers', max_length=50),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.CharField(default='begineers', max_length=50),
        ),
    ]
