# Generated by Django 5.0.4 on 2024-04-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationApi', '0002_articles_level_courses_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='begineers', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('author_image', models.ImageField(upload_to='images')),
                ('date', models.DateField(auto_now=True)),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='date',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='video',
        ),
        migrations.AddField(
            model_name='courses',
            name='link',
            field=models.URLField(default='https://www.coursera.org/learn/python-for-applied-data-science-ai'),
        ),
    ]
